<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th,
        td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }

        th {
            background-color: #f2f2f2;
        }

        .header {
            text-align: center;
            font-size: 18px;
            font-weight: bold;
            margin-bottom: 10px;
        }

        .footer {
            text-align: right;
            font-size: 12px;
            margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="header">Laporan Keuangan Koperasi Konsumen Karlisna PLN Yogyakarta</div>
    <p>Tanggal: {{ $currentDateTime }}</p>

    <table>
        <tr>
            <th>Jenis</th>
            <th>Jumlah (Rp)</th>
        </tr>
        <tr>
            <td>Saldo Pinjaman (Emergency)</td>
            <td>{{ $emergency }}</td>
        </tr>
        <tr>
            <td>Saldo Pinjaman (Angunan)</td>
            <td>{{ $angunan }}</td>
        </tr>
        <tr>
            <td>Saldo Pinjaman (Non-Angunan)</td>
            <td>{{ $nonangunan }}</td>
        </tr>
        <tr>
            <td><strong>Total Pinjaman</strong></td>
            <td><strong>{{ $totalLoans }}</strong></td>
        </tr>
        <tr>
            <td><strong>Total Simpanan</strong></td>
            <td><strong>{{ $simpanan }}</strong></td>
        </tr>
    </table>

    {{-- <div class="footer">
        <p>Generated by System | {{ now()->format('d-m-Y H:i') }}</p>
    </div> --}}
</body>

</html>
